In [3]:
import numpy as np

In [4]:
list = [1,2,3,4,5]
list

[1, 2, 3, 4, 5]

In [5]:
arr = np.array(list)
arr

array([1, 2, 3, 4, 5])

In [6]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr.shape

(5,)

In [8]:
arr2.shape

(2, 3)

In [9]:
print(arr[0])

1


In [10]:
print(arr2[1,2])

6


In [11]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr1[3:8] = 12

In [13]:
arr1

array([ 0,  1,  2, 12, 12, 12, 12, 12,  8,  9])

In [14]:
arr6 = np.arange(50).reshape(5, 10)
arr6

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [20]:
height_weight = np.loadtxt("height_weight.txt", delimiter=",")
height_weight

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])

In [21]:
height = height_weight[0]
weight = height_weight[1]

In [25]:
bmi = weight / (height/100)**2
bmi

array([21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
       20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998])

In [37]:
name_score = np.array(np.random.randint(50, 100, size=8))
name_score

array([96, 73, 75, 96, 83, 53, 76, 90])

In [38]:
name_score >= 80

array([ True, False, False,  True,  True, False, False,  True])

In [39]:
name_score[name_score>=80]

array([96, 96, 83, 90])