In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
arr[[True, True, False]]

array([1, 2])

In [6]:
score = np.array([80, 70, 60, 50, 77, 66, 44, 85])
score

array([80, 70, 60, 50, 77, 66, 44, 85])

In [9]:
bool_data = score >= 60

In [12]:
score[bool_data]

array([80, 70, 60, 77, 66, 85])

In [13]:
arr = np.random.rand(5,4)
print(arr)
print(arr.sum())

[[0.48459015 0.99673737 0.44041154 0.71936792]
 [0.83380034 0.70913914 0.39381279 0.75882606]
 [0.06833395 0.83382646 0.54095053 0.71468107]
 [0.82538781 0.45874803 0.84326783 0.49614125]
 [0.09738464 0.664384   0.16378851 0.53250115]]
11.576080517211766


In [14]:
arr.mean()

0.5788040258605883

In [15]:
arr3 = np.array([-1, 2, -3, 4, -5])
arr3

array([-1,  2, -3,  4, -5])

In [17]:
np.abs(arr3)

array([1, 2, 3, 4, 5])